version: 2
project_name: secret

before:
  hooks:
    - go mod tidy
    - go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
    - goversioninfo -o resource.syso

builds:
  - id: secret-darwin
    main: .
    binary: secret
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/asnowfix/secret/cmd.version={{ .Tag }}

  - id: secret-linux
    main: .
    binary: secret
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/asnowfix/secret/cmd.version={{ .Tag }}

  - id: secret-windows
    main: .
    binary: secret
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -X github.com/asnowfix/secret/cmd.version={{ .Tag }}

archives:
  - id: secret
    name_template: 'secret_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

release:
  draft: false
  prerelease: auto

scoops:
  - name: secret
    repository:
      owner: asnowfix
      name: scoop-secret
    homepage: https://github.com/asnowfix/secret
    description: Cross-platform CLI for native secret stores
    license: Apache-2.0
    skip_upload: auto

winget:
  - name: secret
    publisher: asnowfix
    publisher_url: https://github.com/asnowfix/secret
    publisher_support_url: https://github.com/asnowfix/secret/issues
    homepage: https://github.com/asnowfix/secret
    short_description: Cross-platform CLI for native secret stores
    license: Apache-2.0
    license_url: https://github.com/asnowfix/secret/blob/main/LICENSE
    package_identifier: asnowfix.secret
    repository:
      owner: asnowfix
      name: winget-pkgs
      branch: "secret-{{.Version}}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
    skip_upload: auto
